server:
  port: 9080

spring:
  application:
    name: Fund Transfer
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: diyaan2604.
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: update